[
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "What does a negative ΔG value signify for a chemical reaction?",
    "hint": "Spontaneity depends on Gibbs free energy.",
    "explanation": "A negative ΔG indicates the reaction is spontaneous at the given temperature.",
    "swipe_up_label": "Spontaneous",
    "swipe_right_label": "Equilibrium",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Non-spontaneous",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "If a reaction rate doubles when the temperature increases from 298 K to 308 K, what is the effect on the rate constant k?",
    "hint": "Review the Arrhenius equation.",
    "explanation": "The rate constant increases exponentially with temperature. [Image of Arrhenius equation plot]",
    "swipe_up_label": "k Decreases",
    "swipe_right_label": "k Increases",
    "swipe_down_label": "HINT",
    "swipe_left_label": "k is Constant",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "In a first-order reaction, how does the half-life change with initial concentration?",
    "hint": "t₁/₂ = 0.693 / k.",
    "explanation": "Half-life is independent of initial concentration. [Image of first order reaction half life graph]",
    "swipe_up_label": "Increases",
    "swipe_right_label": "Independent",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Decreases",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "Calculate the E°cell for Zn²⁺/Zn and Cu²⁺/Cu.",
    "hint": "E°cell = E°cathode − E°anode.",
    "explanation": "0.34 − (−0.76) = 1.10 V. [Image of Daniell cell redox reaction]",
    "swipe_up_label": "−0.42 V",
    "swipe_right_label": "1.10 V",
    "swipe_down_label": "HINT",
    "swipe_left_label": "0.42 V",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "At equilibrium, what is the relationship between forward and backward reaction rates?",
    "hint": "Equilibrium is dynamic.",
    "explanation": "Rates are equal with no net change. [Image of equilibrium concentration vs time graph]",
    "swipe_up_label": "Rates are Zero",
    "swipe_right_label": "Rates are Equal",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Forward is faster",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "What is the pH of a 0.001 M HCl solution?",
    "hint": "pH = −log[H⁺].",
    "explanation": "pH equals 3. [Image of pH scale]",
    "swipe_up_label": "pH = 7",
    "swipe_right_label": "pH = 3",
    "swipe_down_label": "HINT",
    "swipe_left_label": "pH = 1",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "Why does a catalyst speed up a reaction?",
    "hint": "Catalysts affect pathway.",
    "explanation": "Lowers activation energy. [Image of reaction energy profile with catalyst]",
    "swipe_up_label": "Changes K",
    "swipe_right_label": "Lowers Ea",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Increases ΔH",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "How does high pressure affect the Haber process?",
    "hint": "Compare gas moles.",
    "explanation": "Shifts equilibrium to fewer moles. [Image of Le Chatelier's principle pressure shift]",
    "swipe_up_label": "Shifts Left",
    "swipe_right_label": "No Effect",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Shifts Right",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "What causes corrosion (rusting) of iron?",
    "hint": "Requires environment.",
    "explanation": "Needs oxygen and moisture. [Image of rusting of iron mechanism]",
    "swipe_up_label": "O₂ and H₂O",
    "swipe_right_label": "H₂O only",
    "swipe_down_label": "HINT",
    "swipe_left_label": "N₂ Gas",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "In electrolysis of brine, what forms at the anode?",
    "hint": "Anode = oxidation.",
    "explanation": "Chlorine gas is formed. [Image of Chlor-alkali process]",
    "swipe_up_label": "H₂ Gas",
    "swipe_right_label": "Cl₂ Gas",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Na Metal",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "Why is helium used in diving tanks?",
    "hint": "Solubility in blood.",
    "explanation": "Lower solubility prevents bends. [Image of Henry's Law graph]",
    "swipe_up_label": "Cheaper Cost",
    "swipe_right_label": "Lower Solubility",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Lighter Weight",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "Radioactive isotope half-life = 6 h. Amount after 24 h?",
    "hint": "24 h = 4 half-lives.",
    "explanation": "6.25% remains. [Image of radioactive decay curve]",
    "swipe_up_label": "12.5%",
    "swipe_right_label": "25%",
    "swipe_down_label": "HINT",
    "swipe_left_label": "6.25%",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "What defines a chiral carbon?",
    "hint": "Count substituents.",
    "explanation": "Four different groups attached. [Image of chiral enantiomers]",
    "swipe_up_label": "4 Unique Groups",
    "swipe_right_label": "Symmetrical",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Double Bonds",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Which alkyl halide reacts fastest in SN2?",
    "hint": "Steric hindrance matters.",
    "explanation": "Least hindered reacts fastest. [Image of SN2 steric hindrance diagram]",
    "swipe_up_label": "Tertiary",
    "swipe_right_label": "Secondary",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Methyl",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "What intermediate forms in SN1?",
    "hint": "Two-step mechanism.",
    "explanation": "Carbocation intermediate. [Image of SN1 reaction mechanism steps]",
    "swipe_up_label": "Carbanion",
    "swipe_right_label": "Free Radical",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Carbocation",
    "correct": "LEFT",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "IUPAC name of CH₃CH₂CH(CH₃)₂?",
    "hint": "Longest chain.",
    "explanation": "2-Methylbutane is correct. [Image of 2-methylbutane structure]",
    "swipe_up_label": "Pentane",
    "swipe_right_label": "Isopentane",
    "swipe_down_label": "HINT",
    "swipe_left_label": "2-Methylbutane",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "Hybridization of carbon in ethene?",
    "hint": "Double bond present.",
    "explanation": "sp² hybridization. [Image of sp2 hybridization in ethene]",
    "swipe_up_label": "sp",
    "swipe_right_label": "sp²",
    "swipe_down_label": "HINT",
    "swipe_left_label": "sp³",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Markovnikov addition of HBr to propene: where does H add?",
    "hint": "More substituted carbocation favored.",
    "explanation": "Adds to carbon with more hydrogens. [Image of Markovnikov addition mechanism]",
    "swipe_up_label": "C3 Carbon",
    "swipe_right_label": "C1 Carbon",
    "swipe_down_label": "HINT",
    "swipe_left_label": "C2 Carbon",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "Polymer from tetrafluoroethene?",
    "hint": "Non-stick polymer.",
    "explanation": "Teflon is formed. [Image of Teflon polymer structure]",
    "swipe_up_label": "Nylon",
    "swipe_right_label": "Teflon",
    "swipe_down_label": "HINT",
    "swipe_left_label": "PVC",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Products of saponification?",
    "hint": "Soap formation.",
    "explanation": "Soap and glycerol formed. [Image of saponification reaction]",
    "swipe_up_label": "Soap + Glycerol",
    "swipe_right_label": "Ester + Water",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Acid + Alcohol",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "Why are CFCs harmful?",
    "hint": "Upper atmosphere chemistry.",
    "explanation": "Cause ozone depletion. [Image of ozone depletion mechanism]",
    "swipe_up_label": "Smog",
    "swipe_right_label": "Ozone Depletion",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Acid Rain",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Salicylic acid + acetic anhydride forms which group?",
    "hint": "Aspirin synthesis.",
    "explanation": "Ester group formed. [Image of aspirin synthesis reaction]",
    "swipe_up_label": "Ether",
    "swipe_right_label": "Amide",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Ester",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "What does high octane rating signify?",
    "hint": "Engine knocking.",
    "explanation": "Resistance to knocking. [Image of engine knocking vs smooth combustion]",
    "swipe_up_label": "Higher Energy",
    "swipe_right_label": "Knock Resistance",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Faster Burning",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Catalyst for hydrogenation of vegetable oils?",
    "hint": "Industrial process.",
    "explanation": "Nickel is used. [Image of hydrogenation of oils mechanism]",
    "swipe_up_label": "Vanadium",
    "swipe_right_label": "Platinum",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Nickel",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Geometry of SF₆?",
    "hint": "Six bond pairs.",
    "explanation": "Octahedral geometry. [Image of octahedral SF6 molecular geometry]",
    "swipe_up_label": "Octahedral",
    "swipe_right_label": "Tetrahedral",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Square Planar",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Hybridization of P in PCl₅?",
    "hint": "Five domains.",
    "explanation": "sp³d hybridization. [Image of trigonal bipyramidal PCl5 geometry]",
    "swipe_up_label": "sp³d",
    "swipe_right_label": "sp³",
    "swipe_down_label": "HINT",
    "swipe_left_label": "sp³d²",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Why are transition metal complexes colored?",
    "hint": "d-orbital splitting.",
    "explanation": "d–d transitions absorb light. [Image of d-orbital splitting in octahedral complex]",
    "swipe_up_label": "d-d Transitions",
    "swipe_right_label": "s-p Overlap",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Ligand Mass",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Oxidation state of Mn in KMnO₄?",
    "hint": "O = −2, K = +1.",
    "explanation": "Oxidation state is +7. [Image of potassium permanganate structure]",
    "swipe_up_label": "+7",
    "swipe_right_label": "+2",
    "swipe_down_label": "HINT",
    "swipe_left_label": "+4",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "What is a strong-field ligand?",
    "hint": "Size of Δ.",
    "explanation": "Produces low-spin complexes. [Image of strong field vs weak field splitting]",
    "swipe_up_label": "Low Spin",
    "swipe_right_label": "High Spin",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Neutral",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Which ion is paramagnetic?",
    "hint": "Unpaired electrons.",
    "explanation": "Fe³⁺ is paramagnetic. [Image of paramagnetic vs diamagnetic electron filling]",
    "swipe_up_label": "Sc³⁺",
    "swipe_right_label": "Zn²⁺",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Fe³⁺",
    "correct": "LEFT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Purpose of froth flotation?",
    "hint": "Sulfide ores.",
    "explanation": "Concentration of ore. [Image of froth flotation process]",
    "swipe_up_label": "Refining",
    "swipe_right_label": "Concentration",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Reduction",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Primary reducing agent in blast furnace?",
    "hint": "Iron extraction.",
    "explanation": "CO reduces iron ore. [Image of blast furnace iron extraction]",
    "swipe_up_label": "Carbon Dioxide",
    "swipe_right_label": "Carbon Monoxide",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Oxygen",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "What does P stand for in N-P-K fertilizer?",
    "hint": "Macronutrients.",
    "explanation": "Phosphorus. [Image of NPK fertilizer nutrient roles]",
    "swipe_up_label": "Lead",
    "swipe_right_label": "Phosphorus",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Potassium",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "How do zeolites soften hard water?",
    "hint": "Ion exchange.",
    "explanation": "Exchange Na⁺ with Ca²⁺/Mg²⁺. [Image of zeolite water softening mechanism]",
    "swipe_up_label": "Ion Exchange",
    "swipe_right_label": "Filtration",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Precipitation",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Main component of stainless steel besides iron?",
    "hint": "Corrosion resistance.",
    "explanation": "Chromium provides resistance. [Image of stainless steel chromium oxide layer]",
    "swipe_up_label": "Chromium",
    "swipe_right_label": "Copper",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Carbon",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Why is AgBr used in photography?",
    "hint": "Light sensitivity.",
    "explanation": "Decomposes on light exposure. [Image of silver halide photolysis]",
    "swipe_up_label": "Developing",
    "swipe_right_label": "Light Sensitivity",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Reflectivity",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "Reference standard in NMR?",
    "hint": "0 ppm reference.",
    "explanation": "TMS is reference. [Image of TMS NMR peak]",
    "swipe_up_label": "TMS",
    "swipe_right_label": "Benzene",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Water",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "IR peak at 1710 cm⁻¹ indicates?",
    "hint": "Strong sharp peak.",
    "explanation": "Carbonyl group. [Image of IR spectrum carbonyl peak]",
    "swipe_up_label": "Carbonyl",
    "swipe_right_label": "Alkane",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Alcohol",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "What is molecular ion peak in MS?",
    "hint": "M⁺ peak.",
    "explanation": "Represents intact molecule. [Image of mass spectrum molecular ion peak]",
    "swipe_up_label": "Molecular Ion",
    "swipe_right_label": "Fragment",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Base Peak",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "pH at equivalence of HCl vs NaOH titration?",
    "hint": "Strong acid–base.",
    "explanation": "pH equals 7. [Image of titration curve strong acid strong base]",
    "swipe_up_label": "pH = 9",
    "swipe_right_label": "pH = 7",
    "swipe_down_label": "HINT",
    "swipe_left_label": "pH = 4",
    "correct": "RIGHT",
    "weight": 2
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "Beer–Lambert law: absorbance proportional to?",
    "hint": "A = εcl.",
    "explanation": "Proportional to concentration. [Image of Beer-Lambert law plot]",
    "swipe_up_label": "Volume",
    "swipe_right_label": "Concentration",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Temperature",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "What does BOD measure?",
    "hint": "Water pollution.",
    "explanation": "Oxygen demand of microbes. [Image of BOD test process]",
    "swipe_up_label": "Oxygen Demand",
    "swipe_right_label": "CO₂ Levels",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Mineral Content",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "How is Rf calculated in chromatography?",
    "hint": "TLC principle.",
    "explanation": "Solute distance / solvent distance. [Image of TLC Rf value calculation]",
    "swipe_up_label": "Solute / Solvent",
    "swipe_right_label": "Mass Ratio",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Solvent / Solute",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "Preservative tested in soft drinks by HPLC?",
    "hint": "Antifungal agent.",
    "explanation": "Sodium benzoate. [Image of HPLC chromatogram food additives]",
    "swipe_up_label": "Salt",
    "swipe_right_label": "Sodium Benzoate",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Glucose",
    "correct": "RIGHT",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "Why measure soil pH in agriculture?",
    "hint": "Crop nutrition.",
    "explanation": "Determines nutrient availability. [Image of soil pH nutrient availability chart]",
    "swipe_up_label": "Nutrient Access",
    "swipe_right_label": "Density",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Moisture",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "Purpose of blank in spectrophotometry?",
    "hint": "Instrument zeroing.",
    "explanation": "Subtracts solvent absorbance. [Image of spectrophotometer zeroing with blank]",
    "swipe_up_label": "Zeroing",
    "swipe_right_label": "Coloring",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Calibration",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Mixed",
    "q_type": "CONCEPT",
    "question_text": "Which factor favors SN2 over SN1?",
    "hint": "Substrate + solvent.",
    "explanation": "Primary halide in aprotic solvent. [Image of SN2 backside attack mechanism]",
    "swipe_up_label": "Primary + Aprotic",
    "swipe_right_label": "Protic Solvent",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Tertiary Halide",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Mixed",
    "q_type": "APPLICATION",
    "question_text": "ΔH = −100 kJ, ΔS = −200 J/K. When non-spontaneous?",
    "hint": "T = ΔH/ΔS.",
    "explanation": "Above 500 K. [Image of Gibbs free energy spontaneity vs temperature]",
    "swipe_up_label": "500 K",
    "swipe_right_label": "100 K",
    "swipe_down_label": "HINT",
    "swipe_left_label": "250 K",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Mixed",
    "q_type": "CONCEPT",
    "question_text": "How is pool pH maintained after chlorine addition?",
    "hint": "Acid formed.",
    "explanation": "Soda ash added. [Image of swimming pool water chemistry balance]",
    "swipe_up_label": "Add Soda Ash",
    "swipe_right_label": "Add Salt",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Add Acid",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Mixed",
    "q_type": "APPLICATION",
    "question_text": "Role of limestone in blast furnace?",
    "hint": "Slag formation.",
    "explanation": "Acts as flux. [Image of slag formation in blast furnace]",
    "swipe_up_label": "Flux for Slag",
    "swipe_right_label": "Carbon Source",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Reducing Agent",
    "correct": "UP",
    "weight": 2
  }
]
