[
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "SI unit of enthalpy?",
    "hint": "Energy per mole.",
    "explanation": "kJ/mol is correct because enthalpy is energy change per mole.",
    "swipe_up_label": "kJ/mol",
    "swipe_right_label": "J/K",
    "swipe_down_label": "HINT",
    "swipe_left_label": "eV",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "Bond type in alkanes?",
    "hint": "Single bonds only.",
    "explanation": "Alkanes contain only sigma bonds.",
    "swipe_up_label": "Sigma",
    "swipe_right_label": "Pi",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Hydrogen bond",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Common oxidation state of Na?",
    "hint": "Alkali metal.",
    "explanation": "Sodium loses one electron to form +1 state.",
    "swipe_up_label": "1",
    "swipe_right_label": "2",
    "swipe_down_label": "HINT",
    "swipe_left_label": "0",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "pH range of acids?",
    "hint": "Less than neutral.",
    "explanation": "Acids have pH values less than 7.",
    "swipe_up_label": "<7",
    "swipe_right_label": "7",
    "swipe_down_label": "HINT",
    "swipe_left_label": ">7",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Physical",
    "q_type": "CONCEPT",
    "question_text": "Isothermal process keeps?",
    "hint": "Temperature constant.",
    "explanation": "In an isothermal process temperature remains constant.",
    "swipe_up_label": "Temperature",
    "swipe_right_label": "Pressure",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Volume",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Organic",
    "q_type": "CONCEPT",
    "question_text": "Functional group of alcohol?",
    "hint": "Contains oxygen.",
    "explanation": "Alcohols contain the hydroxyl group.",
    "swipe_up_label": "-OH",
    "swipe_right_label": "-COOH",
    "swipe_down_label": "HINT",
    "swipe_left_label": "-CHO",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Inorganic",
    "q_type": "CONCEPT",
    "question_text": "Color of CuSO4·5H2O?",
    "hint": "Hydrated copper salt.",
    "explanation": "Hydrated copper sulfate appears blue.",
    "swipe_up_label": "Blue",
    "swipe_right_label": "Green",
    "swipe_down_label": "HINT",
    "swipe_left_label": "White",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_A",
    "topic": "Analytical",
    "q_type": "CONCEPT",
    "question_text": "End point in titration means?",
    "hint": "Indicator change.",
    "explanation": "End point is identified by indicator color change.",
    "swipe_up_label": "Completion",
    "swipe_right_label": "Start",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Excess",
    "correct": "UP",
    "weight": 1
  },
  {
    "dataset": "SET_B",
    "topic": "Physical",
    "q_type": "APPLICATION",
    "question_text": "Gas expands on heating due to?",
    "hint": "Kinetic theory.",
    "explanation": "Heating increases kinetic energy of gas molecules.",
    "swipe_up_label": "Kinetic energy",
    "swipe_right_label": "Mass",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Fewer collisions",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Organic",
    "q_type": "APPLICATION",
    "question_text": "Test for alkene?",
    "hint": "Unsaturation check.",
    "explanation": "Bromine water decolorizes in presence of alkene.",
    "swipe_up_label": "Bromine water",
    "swipe_right_label": "Fehling",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Tollens",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Inorganic",
    "q_type": "APPLICATION",
    "question_text": "Metal used for galvanization?",
    "hint": "Sacrificial protection.",
    "explanation": "Zinc protects iron from corrosion.",
    "swipe_up_label": "Zinc",
    "swipe_right_label": "Copper",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Iron",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_B",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "Method to separate dyes?",
    "hint": "Differential adsorption.",
    "explanation": "Chromatography separates components based on adsorption.",
    "swipe_up_label": "Chromatography",
    "swipe_right_label": "Filtration",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Distillation",
    "correct": "UP",
    "weight": 2
  },
  {
    "dataset": "SET_D",
    "topic": "Analytical",
    "q_type": "APPLICATION",
    "question_text": "Why internal standard used?",
    "hint": "Error correction.",
    "explanation": "Internal standards compensate for measurement losses.",
    "swipe_up_label": "Error correction",
    "swipe_right_label": "Noise",
    "swipe_down_label": "HINT",
    "swipe_left_label": "Impurity",
    "correct": "UP",
    "weight": 3
  }
]
